Курсовая за 1 курс
DimAshQZ/home-works-sds pull request #1
Opened 2021-11-04 20:46 UTC by DimAshQZ

Изначально по незнанию программировал на https://github.com/DimAshQZ/SkyProCourseworkJava.git. Вся история храниться там.
Было интересно.
Не смог реализовать удаление по ID.

2021-11-08 12:53 UTC, DisterRU requested changes

2021-11-08 12:53 UTC, DisterRU commented on src/pro/sky/java/cource1/coursework/EmployeeBook.java
> +        Arrays.stream(employees).forEach(System.out::println);
А если работники не заполнены, будет напечатано большое количество нуллов.
Рекомендую переписать с циклом и корректно.
Стримы использовать не рекомендую до дз по стримам.

2021-11-08 12:53 UTC, DisterRU commented on src/pro/sky/java/cource1/coursework/EmployeeBook.java
> +        return Arrays.stream(employees).mapToDouble(Employee::getSalary).sum();
Опять стрим использован некорректно.
В случае с nullом вылетит NullPointerException при попытке конвертации в double.
Заменить на цикл.

2021-11-08 12:53 UTC, DisterRU commented on src/pro/sky/java/cource1/coursework/EmployeeBook.java
> +        double minSalary = Integer.MAX_VALUE;
Раз тип double, причем тут Integer?
Нужно использовать Double.MAX_VALUE

2021-11-08 12:53 UTC, DisterRU commented on src/pro/sky/java/cource1/coursework/EmployeeBook.java
> +        return calcSalarySum() / employees.length;
Откуда уверенность, что массив полностью заполнен сотрудниками?
Нужно делить на фактическое количество, а не на размер хранилища.

2021-11-08 12:53 UTC, DisterRU commented on src/pro/sky/java/cource1/coursework/EmployeeBook.java
> +        Arrays.stream(employees).map(employee -> employee.getId() + ") " + employee.getName()).forEach(System.out::println);
NullPointerException при попытке вызвать getId у null.
Переписать на цикл.

2021-11-08 12:53 UTC, DisterRU commented on src/pro/sky/java/cource1/coursework/EmployeeBook.java
> +        for (Employee employee : employees) employee.setSalary(percent / 100 * employee.getSalary());
Циклы в одну строчку писать очень плохо.
Нужно тело цикла писать с новой строки, обернув в скобки.

2021-11-08 12:53 UTC, DisterRU commented on src/pro/sky/java/cource1/coursework/EmployeeBook.java
> +        return Arrays.stream(employees).filter(employee -> employee.getDepartment() == department).mapToDouble(Employee::getSalary).sum();
NullPointerException.
Переписать на цикл.

2021-11-08 12:53 UTC, DisterRU commented on src/pro/sky/java/cource1/coursework/EmployeeBook.java
> +                count += 1;
count++

2021-11-08 12:53 UTC, DisterRU commented on src/pro/sky/java/cource1/coursework/EmployeeBook.java
> +        Arrays.stream(employees).filter(value -> value.getDepartment() == department).forEach(employee -> employee.setSalary(percent / 100 * employee.getSalary()));
NullPointerException.
Переписать на цикл.

2021-11-08 12:53 UTC, DisterRU commented on src/pro/sky/java/cource1/coursework/EmployeeBook.java
> +        }
Зачем тут нужен флаг empty?
Находим пустую ячейку, кладем туда нашего newEmployee, увеличиваем size (хотя я не особо заметил его использование в коде) и делаем return.
В противном случае (когда свободной ячейки нет и return не был вызван) пишем сообщение, что все плохо и ничего не получилось.

2021-11-08 12:53 UTC, DisterRU commented on src/pro/sky/java/cource1/coursework/EmployeeBook.java
> +    }
Этот вариант удалить.

2021-11-08 12:53 UTC, DisterRU commented on src/pro/sky/java/cource1/coursework/EmployeeBook.java
> +    }*/
В этот вариант добавить проверку, что employees[i] != null.
Только после этого проверять id.
По аналогии реализовать удаление по имени.

2021-11-08 12:53 UTC, DisterRU commented on src/pro/sky/java/cource1/coursework/EmployeeBook.java
> +    public void employeesByDepartment() {
Метод должен начинаться с глагола в имени.

2021-11-08 12:53 UTC, DisterRU commented on src/pro/sky/java/cource1/coursework/EmployeeBook.java
> +        }
Вообще не понимаю смысла этого цикла.
В тз указано, что отделы идут от 1 до 5.

2021-11-10 06:59 UTC, DimAshQZ commented on src/pro/sky/java/cource1/coursework/EmployeeBook.java
> +        }
Привет. Согласен что выглядит костыльно. Переменная empty тут  для проверки пустых ячеек если их нет то добавляться новая. Это нужно для первичного заполнения. Сижу, ломаю голову как переиначить подскажи, пожалуйста?!

2021-11-14 16:52 UTC, DisterRU requested changes

2021-11-14 16:52 UTC, DisterRU commented on src/pro/sky/java/course1/courseWork/Coursework.java
> +package pro.sky.java.course1.courseWork;
Пакеты в Java не могут содержать больших букв.
Нужно вернуть к старому варианту.

2021-11-14 16:52 UTC, DisterRU commented on src/pro/sky/java/course1/courseWork/EmployeeBook.java
> +            sum += salary;
Следует сократить до sum += employee.getSalary().

2021-11-14 16:52 UTC, DisterRU commented on src/pro/sky/java/course1/courseWork/EmployeeBook.java
>      public Employee minSalaryEmployee() {
Методы должны именоваться с глагола.

2021-11-14 16:52 UTC, DisterRU commented on src/pro/sky/java/course1/courseWork/EmployeeBook.java
>      public double averageSalary() {
Методы должны именоваться с глагола.

2021-11-14 16:52 UTC, DisterRU commented on src/pro/sky/java/course1/courseWork/EmployeeBook.java
>      public void allEmployeesName() {
Методы должны именоваться с глагола.

2021-11-14 16:52 UTC, DisterRU commented on src/pro/sky/java/course1/courseWork/EmployeeBook.java
>      public void indexationOfWages(double percent) {
Методы должны именоваться с глагола.

2021-11-14 16:52 UTC, DisterRU commented on src/pro/sky/java/course1/courseWork/EmployeeBook.java
>      public Employee minSalaryEmployeeOfDepartment(int department) {
Методы должны именоваться с глагола.

2021-11-14 16:52 UTC, DisterRU commented on src/pro/sky/java/course1/courseWork/EmployeeBook.java
>      public void indexationOfWages(double percent) {
Проценты принято передавать в целых числах.

2021-11-14 16:52 UTC, DisterRU commented on src/pro/sky/java/course1/courseWork/EmployeeBook.java
> +                sum += salary;
sum += employee.getSalary()

2021-11-14 16:52 UTC, DisterRU commented on src/pro/sky/java/course1/courseWork/EmployeeBook.java
> +        for (Employee value : employees) {
Очень плохое имя value.
Следует переименовать в employee.

2021-11-14 16:52 UTC, DisterRU commented on src/pro/sky/java/course1/courseWork/EmployeeBook.java
> +                if (employees[i].getId() == id) {
Зачем плодить вложенность?
Следует использовать один блок if и логическое И (&&)

2021-11-22 22:07 UTC, DisterRU approved these changes

2021-11-22 22:07 UTC, DisterRU commented on src/pro/sky/java/course1/coursework/EmployeeBook.java
> +            employee.setSalary(employee.getSalary() + (employee.getSalary() * percent / 100));
Лучше делить такой код на несколько строк.
В одной достаем текущую зп, во второй считаем увеличение, в третьей задаем новую зп.

2021-11-24 08:41 UTC, merged